### ISSUE TITLE
Thanks, thoughts?

### ISSUE THREAD

**Issue by zoz** [mark-hahn/drykup#1]
Hi Mark,
Thank you for providing drykup, I enjoy the straight forward implementation.  I was wondering if you have been using it much and if so what is your experience with it?  Did you go back to CoffeeCup for any reason?
Thanks,
Zoz

(I put this as a issue because your github messaging is disabled, i hope you don't mind)

**Comment by mark-hahn** [comment]
Yes I have been using it every day since I wrote it.  I have an app about
to go into beta that uses only drykup.  I probably have a few thousand
lines of it.

When I wrote it I was worried about the need to declare all the tags, but
that has turned out to be no problem at all.  I declare the needed tags at
the top of each module, and it is surprising how few are needed.

The version I'm using has been patched without the github version being
updated, although there have been no bugs.  I didn't think there was any
interest in drykup so I haven't taken the trouble to maintain the repo
properly.

I'm thinking of doing a new version that doesn't even generate HTML but
adds the tags directly to the dom.  I read a great article about how that
is faster than generating the html text first.

http://blog.fastmail.fm/2012/02/20/building-the-new-ajax-mail-ui-part-2-better-than-templates-building-highly-dynamic-web-pages/

This would be a good fit for me because my pages are loaded mostly empty
and then generate html as it is needed.  I would still need to maintain the
current version because I still generate some html on the server.

And of course I also have a lot of wild feature ideas for the new version.
 The wildest one is to include the functionality of knockout.  Knockout
bindings are specified in the dom and there is a great opportunity to do
knockout in a more elegant way.

On Fri, Mar 9, 2012 at 9:42 AM, Zoz <
reply@reply.github.com>
wrote:

**Comment by zoz** [comment]
Awesome, I like it!  Thanks for the quick feedback.  I have been doing a similar approach with a library I wrote.  But now that I found drykup I will use your code instead.  
Declaring the tags at top is no problem for me too.  I really like how easy it is to extend drykup:

```
js = (srcname) ->
  drykup.normalTag 'script', [ type:'text/javascript', src:"#{srcname}", '' ]
```

If I come up with any cool changes or additions I will let you know.
Thanks!
Zoz
