### ISSUE TITLE
No issues? How's it working out?

### ISSUE THREAD

**Issue by asalant** [mark-hahn/drykup#3]
Hey Mark,

We're considering switching from coffeekup (actually, the maintained coffeecup fork at https://github.com/gradus/coffeecup) to drykup and I'm wondering how it's working out for you. Doesn't look like there are any recent commits. Are you still using it? Any issues?

Thanks!

**Comment by mark-hahn** [comment]
I've been using it for a long time and haven't felt any need to change it.
 It is quite simple.

Apparently very few people, if any, are using it.  I don't know why
everyone is so hooked on traditional templates.  I find them hard to read.

Since I'm still using it I would be happy to support it.  I have no plans
to replace it with anything else.

Let me know if it works out for you.  I'm especially curious to see if you
use the expansion feature.  It is pretty insane but I love it.

**Comment by mark-hahn** [comment]
I just realized the docs say it is still in alpha.  Maybe that's why nobody is using it.  Duh.

**Comment by asalant** [comment]
Mark - thanks for the additional info!

Re: expansions
I took a look at the source and was a bit surprised to see that in there. I haven't put style attributes in my markup in a long time so wouldn't use those and am pretty sure I prefer the clear mapping to html attributes for the rest.

My primary interest is in having closure scope available in my templates which you loose with coffeekup.

Also, I looked at the test dir and noticed that they are just harnesses for doing a visual check, not automated tests. If I were to contribute features or bug fixes, I'd be psyched if there were an existing test suite to add to. If you're interested in having others use drykup, I believe that having a test suite is an important mark of quality. I know I look for it when considering modules to bring in to my projects.

**Comment by mark-hahn** [comment]
>  I looked at the test dir

I know I haven't done a good job of making this published quality.  When I
get between projects I'll spend some time on it.  I should at least update
it's status now.

Any help would be appreciated. :-)

**Comment by asalant** [comment]
Great. Will let you know how it goes. I expect we'll have pull requests for you if/when we start using it.

**Comment by mark-hahn** [comment]
BTW, I should mention that one drykup improvement, actually a major change,
I've been considering is outputting DOM elements directly instead of HTML
text when in the client.  I have read several places that this is faster
than producing and processing the HTML.

I don't know about you, but my client drykup usage always uses jquery to
convert to elements immediately after getting the html text.  This concept
fits nicely with how drykup already generates things directly instead of
building a template function.

This would actually mean that a different version of drykup would be used
in the client than in the server.  Or maybe the generation code would be so
small that it could optionally generate either one.

**Comment by asalant** [comment]
Hey Mark, I wanted to follow up on this discussion. We took a look at drykup's features and what we wanted to do with it and decided that we were going to change so much that it made more sense to introduce yet another fork to the native coffeescript templating ecosystem - http://goodeggs.github.com/teacup.

Teacup uses a similar strategy to drykup by exporting tags explicitly. We decided that since we were already using CoffeeCup we wanted very one-to-one compatibility so we pulled in the full CoffeeCup test suite and implemented a number of features to conform to it's behavior. ID and class selector shortcuts and a coffeescript tag are examples of that. We also added a helper for rendering as Express views and a Rails gem so you can use it in the Rails asset pipeline.

Check it out and let me know what you think - no attribute shortcuts though ;-( 

Thanks for your great work on drykup.

Alon

**Comment by mark-hahn** [comment]
Thanks for the update.  I'll take a look at teacup.  If it keeps the
closure I'm all for it.

I can always add the attr/style shortcuts.  Do you want a pull request?  :-)

P.S.  Nice page.  I've always wondered how developers can make such
good-looking web pages.  I couldn't do anything like that.  Is there any
special tool or service you used?

**Comment by mark-hahn** [comment]
Actually, teacup looks very nice.  I think I'll switch.  You've obviously
put a lot more thinking and work into it than I ever did for drykup.  My
only contribution to the art was using real functions with closure support.

I really will add my shortcuts.  I know that no one else would be insane
enough to use them but i couldn't live without then now.  I'll have to
figure out how to make the shortcuts a separate module that can work
anywhere, not just in teacup.

P.S. Your webpage looks great.  I've never understood how developers could
make such nice websites.  I never could.  Did you use any particular tool
or service?

**Comment by mark-hahn** [comment]
BTW, what do you think of the idea of outputting DOM elements instead of
text/html?  I really believe in this concept.  It wouldn't make much sense
in teacup but maybe I'll make a source-compatible version for the browser.

I myself mostly use drykup in the browser.  I generate everything on the
fly.  Virtually no html comes from the server.  I even recreate html over
and over for things like popups.  It is surprising how well it works.

I'm sorry if I'm spamming your inbox.  Just thinking out loud.

**Comment by asalant** [comment]
Hey, glad you like our work!

Re: project site
We're using http://documentup.com.

Re: attribute shortcuts
I'm inclined to keep it out of the teacup core but we've discussed that it may make sense for teacup to have an explicit extension/plugin model. You could use this to register new tags or change behavior in other ways. If there are changes to teacup that would make it easier to plug in your attribute shortcuts, we'd be happy to support them.

Re: outputting DOM elements
Neat idea but haven't seen a compelling use in practice. When we use teacup on the client, we're using setting inner html with jQuery.html/append/... so the conversion to DOM elements is implicit. We haven't looked closely at performance yet either.

**Comment by mark-hahn** [comment]
> I'm inclined to keep it out of the teacup core

I assumed that.  I didn't mean to suggest it.  I keep thinking there may be
some middle ground for the shortcuts where they could be useful without
being so hard to read.  I guess they should be a feature in an editor where
they are input-only.

> so the conversion to DOM elements is implicit. We haven't looked closely
> at performance yet either.

I don't know if I could find it, but I read a good article that argued for
direct DOM creation.  The author  claimed it was higher performance and had
some other reason I can't remember.  I do know it is much faster to
generate elements in isolation and then add them to the DOM, but you can do
that with html also.  I'm a big believer in simplicity, which is how I came
up with drykup.

Having said that, I doubt one could perceive a performance difference in
the browser.

P.S. I realized later that your webpage was generated by github, right?  I
wasn't aware of the feature.
